### ISSUE TITLE
Issue running Biowdl Germline-DNA v4.1.0: unusable runtime struct initializer

### ISSUE THREAD

**Issue by rhpvorderman** [chanzuckerberg/miniwdl#580] opened 2022-08-02 13:37 UTC
Full error:

```
workflow Germline (germline.wdl Ln 34 Col 1) failed :: dir: "/exports/sasc/rhpvorderman/testminiwdl/germline-dna/20220802_153134_Germline", error: "EvalError", message: "unusable runtime struct initializer (member type mismatch, lacking required member, or extra member)", node: "call-sampleWorkflow-0", pos: {"source": "/exports/sasc/rhpvorderman/testminiwdl/germline-dna/germline.wdl", "line": 119, "column": 26}
```

The WDL file and its imports can be downloaded here: https://github.com/biowdl/germline-DNA/releases/tag/v4.1.0 (germline_v4.1.0.wdl and its accompanying imports zip). 

It works fine in Cromwell. There are some optional members in the structs that we use. Apparently miniwdl cannot handle that properly. Unfortunately I cannot get a more descriptive error message regarding which member.

**Comment by mlin** [comment] 2022-08-03 05:01
@rhpvorderman Can you take a closer look (or share) the JSON being provided for `SampleConfig`?

The most common cause of this discrepancy is that miniwdl rejects "extra" keys in a JSON dict not matching any field of the struct. For example if your struct has an optional field, and your JSON has a typo in the key name, miniwdl will reject it while Cromwell will proceed and just leave the optional field null. The expected behavior is not specified AFAIK & miniwdl tends to be a little more strict as usual.

(That stated, the code that checks this has been revised relatively recently, so it's also possible it's a bug -- we'd know by examining the JSON)

**Comment by rhpvorderman** [comment] 2022-08-03 09:35
This is the JSON
```
{
  "samples": [
    {
      "readgroups": [
        {
          "id": "rg1",
          "R1": "tests/data/wgs1/R1.fq.gz",
          "R1_md5": "b859d6dd76a6861ce7e9a978ae2e530e",
          "R2": "tests/data/wgs1/R2.fq.gz",
          "R2_md5": "986acc7bda0bf2ef55c52431f54fe3a9",
          "lib_id": "lib1"
        }
      ],
      "id": "wgs1-paired-end",
      "control": null
    },
    {
      "readgroups": [
        {
          "id": "rg1",
          "R1": "tests/data/wgs2/wgs2-lib1_R1.fq.gz",
          "R1_md5": "6fb02af910026041f9ea76cd28968732",
          "R2": "tests/data/wgs2/wgs2-lib1_R2.fq.gz",
          "R2_md5": "537ffc52342314d839e7fdd91bbdccd0",
          "lib_id": "lib1"
        },
        {
          "id": "rg2",
          "R1": "tests/data/wgs2/wgs2-lib2_R1.fq.gz",
          "R1_md5": "df64e84fdc9a2d7a9301f2aac0071aee",
          "R2": "tests/data/wgs2/wgs2-lib2_R2.fq.gz",
          "R2_md5": "47a65ad648ac08e802c07669629054ea",
          "lib_id": "lib1"
        }
      ],
      "id": "wgs2-paired-end",
      "control": "wgs1-paired-end"
    }
  ]
}
```
And these are the structs
```WDL
struct Readgroup {
    String id
    String lib_id
    File R1
    File? R2
}

struct Sample {
    String id
    String? control
    String? gender
    Array[Readgroup] readgroups
}

struct SampleConfig {
    Array[Sample] samples
}
```

Ah I see. Gender is missing from the json. So MiniWDL insists on the optional field being present and set to null, which sort of beats the use for an optional field :/.

**Comment by mlin** [comment] 2022-08-03 19:24
I think the issue is more likely the extra `R1_md5` and `R2_md5` keys in the JSON but not the struct. In any case, clearly the error message needs improvement at the least.

**Comment by rhpvorderman** [comment] 2022-08-05 07:56
Ah thanks! Simply updating the struct to include those solved the issue.

Given our recent efforts to port miniwdl to SLURM it is good that we start testing cromwell on both miniwdl and cromwell in order to eliminate any engine-specific stuff in our WDLs. Thank you for your help.

**Comment by rhpvorderman** [comment] 2022-08-05 13:53
Hi, sorry to reopen this.
I have a similar error now with the `gender` member of the struct. That is not defined in the JSON. As a result MiniWDL crashes on `gender = select_first([sample.gender, "unknown"]),` in the wdl file.
So miniwdl does not complain about undefined Struct members in the JSON if they are optional, but also does not add them to the struct and set them to `None`. The latter option is preferred to complaining in my opinion.

**Comment by mlin** [comment] 2022-08-05 20:17
Thanks @rhpvorderman, I've been hacking on this and adjacent issues in https://github.com/chanzuckerberg/miniwdl/pull/581 . The nulls are supposed to be filled in but I think the bug here is specifically around loading *arrays of* structs from JSON, which we didn't have a good test case for previously.

**Comment by mlin** [comment] 2022-08-07 08:49
@rhpvorderman I merged fixes for a number of related issues onto the main branch, please give it a try if you have a chance. I plan to cut a release soon, hopefully to include any unblocking changes to singularity (see [discussion](https://github.com/chanzuckerberg/miniwdl/pull/579#issuecomment-1207164522))

**Comment by rhpvorderman** [comment] 2022-08-08 09:36
Yes #581 Solved this particular issue on the germline-dna pipeline. Great, thanks!

**Closed** 2022-08-08 10:12 UTC
Labels: interop
